### ISSUE TITLE
Create a data directory - store election2020_articles as csv

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/Python-Web-Scraping-Legacy#5]
Creating a data directory with the election2020_articles.csv file within.

Configure the pandas.read_csv(path) to it within the API_workbook.ipynb 

Consider saving as a .csv (if compact enough) in order to avoid confusion for students who don't know what .pkl files are/how to use them.

**Comment by georgeberkeley** [comment]
You're right about the read_csv, however I used .pkl because of the nested lists/dictionaries in the dataframe. If you save a dataframe with lists and dictionaries as a csv, when you read that file back into pandas, it will transform that into a string representation. I'll try to see if I save it as a json of that works better

The article schema table is effectively a data dictionary for that file.

**Comment by seanmperez** [comment]
Yea, that makes a lot of sense! You can’t store that nested structure in a csv.
